microorganisme_index:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:MicroOrganisme:index" }
    methods:  GET

microorganisme_show:
    path:     /{id}/show
    defaults: { _controller: "MoteurRechercheBundle:MicroOrganisme:show" }
    methods:  GET

microorganisme_new:
    path:     /new
    defaults: { _controller: "MoteurRechercheBundle:MicroOrganisme:new" }
    methods:  [GET, POST]

microorganisme_edit:
    path:     /{id}/edit
    defaults: { _controller: "MoteurRechercheBundle:MicroOrganisme:edit" }
    methods:  [GET, POST]

microorganisme_delete:
    path:     /{id}/delete
    defaults: { _controller: "MoteurRechercheBundle:MicroOrganisme:delete" }
    methods:  DELETE
