principemethode_index:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:PrincipeMethode:index" }
    methods:  GET

principemethode_show:
    path:     /{id}/show
    defaults: { _controller: "MoteurRechercheBundle:PrincipeMethode:show" }
    methods:  GET

principemethode_new:
    path:     /new
    defaults: { _controller: "MoteurRechercheBundle:PrincipeMethode:new" }
    methods:  [GET, POST]

principemethode_edit:
    path:     /{id}/edit
    defaults: { _controller: "MoteurRechercheBundle:PrincipeMethode:edit" }
    methods:  [GET, POST]

principemethode_delete:
    path:     /{id}/delete
    defaults: { _controller: "MoteurRechercheBundle:PrincipeMethode:delete" }
    methods:  DELETE
