secteur_index:
    path:     /
    defaults: { _controller: "MoteurRechercheBundle:Secteur:index" }
    methods:  GET

secteur_show:
    path:     /{id}/show
    defaults: { _controller: "MoteurRechercheBundle:Secteur:show" }
    methods:  GET

secteur_new:
    path:     /new
    defaults: { _controller: "MoteurRechercheBundle:Secteur:new" }
    methods:  [GET, POST]

secteur_edit:
    path:     /{id}/edit
    defaults: { _controller: "MoteurRechercheBundle:Secteur:edit" }
    methods:  [GET, POST]

secteur_delete:
    path:     /{id}/delete
    defaults: { _controller: "MoteurRechercheBundle:Secteur:delete" }
    methods:  DELETE
