MoteurRechercheBundle\Entity\Laboratoire:
    type: entity
    table: null
    repositoryClass: MoteurRechercheBundle\Repository\LaboratoireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomLaboratoire:
            type: string
            length: 255
            nullable: true
    oneToMany:
        analyses:
            targetEntity: Analyse
            mappedBy: laboratoire
    lifecycleCallbacks: {  }
