MoteurRechercheBundle\Entity\PrincipeMethode:
    type: entity
    table: null
    repositoryClass: MoteurRechercheBundle\Repository\PrincipeMethodeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomPrincipeMethode:
            type: string
            length: 255
            nullable: true
    oneToMany:
        analyses:
            targetEntity: Analyse
            mappedBy: principeMethode
    lifecycleCallbacks: {  }
