MoteurRechercheBundle\Entity\RenseignementClinique:
    type: entity
    table: null
    repositoryClass: MoteurRechercheBundle\Repository\RenseignementCliniqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        valeurRC:
            type: string
            length: 255
            nullable: true
    oneToMany:
        analyses:
            targetEntity: Analyse
            mappedBy: renseignementClinique
    lifecycleCallbacks: {  }
