<?php

namespace MoteurRechercheBundle\Repository;

/**
 * ConditionPrelevementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionPrelevementRepository extends \Doctrine\ORM\EntityRepository
{
}
