<?php

namespace MoteurRechercheBundle\Repository;

/**
 * ConservationAvantTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConservationAvantTransportRepository extends \Doctrine\ORM\EntityRepository
{
}
