<?php

namespace MoteurRechercheBundle\Repository;

/**
 * DelaiResultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelaiResultatRepository extends \Doctrine\ORM\EntityRepository
{
}
