<?php

namespace MoteurRechercheBundle\Repository;

/**
 * FichePrescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichePrescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
