<?php

namespace MoteurRechercheBundle\Repository;

/**
 * NatureMatriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureMatriceRepository extends \Doctrine\ORM\EntityRepository
{
}
