<?php

namespace MoteurRechercheBundle\Repository;

/**
 * NaturePrelevementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaturePrelevementRepository extends \Doctrine\ORM\EntityRepository
{
}
