<?php

namespace MoteurRechercheBundle\Repository;

/**
 * PrincipeMethodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrincipeMethodeRepository extends \Doctrine\ORM\EntityRepository
{
}
