<?php

namespace MoteurRechercheBundle\Repository;

/**
 * RenseignementCliniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenseignementCliniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
